package enumpackage;

public enum ExpenseTypeEnum {

	ACCOMMOD_RECEIPT, ACCOMMOD_NO_RECEIPT, TRANSP_BUS, TRANSP_CAR, TRANSP_HSR_RECEIPT, TRANSP_HSR_NO_RECEIPT, TRANSP_MRT, TRANSP_TAXI, TRANSP_TRAIN, MEAL, OTHER

}
